eureka_hostname: service-registry
mongodb_hostname: product-db

# Production environment
#mongodb_database_name: productDB

# Development environment
mongodb_database_name: devProductDB

# Test environment
#mongodb_database_name: testProductDB

# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8094

# Application properties
spring:
  application:
    name: PRODUCT-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
# Import configuration from settings.yml
  config:
    import: optional:settings.yml
